FORMAT: 1A
HOST: http://localhost

# Tiesti
API for managing name/value configurations.

# Group Notes
TODO

## Configurations Collection [/configs]
### List all Configurations [GET]
+ Response 200 (application/json)

        [{
          "id": 1
        }, {
          "id": 2
        }]

### Create a Configuration [POST]
+ Request (application/json)

        { 
            "properties": {
                "key" : {
                    "value" : "[actual value]",
                    "root" : "[literal|variable]"
                }
            }
        }

+ Response 201 (application/json)

        { "id": 3 }

## Configuration [/configs/{id}]
A single configuration object with all its details

+ Parameters
    + id (required, string, `1`) ... String identifier for the configuration.

### Retrieve a Configuration [GET]
+ Response 200 (application/json)

    + Body

            {
                "id" : id,
                "properties": {
                    "key" : {
                        "value" : "[actual value]",
                        "root" : "[literal|variable]"
                    }
                }
            }

### Remove a Configuration [DELETE]
+ Response 204
